"""
Django settings for eye project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# 导入debug_toolbar模块  用来调试
import pathlib
import os
import pymysql
LOGIN_URL = '/login/'
pymysql.install_as_MySQLdb()
DEBUG = False
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 将debug_toolbar添加到INSTALLED_APPS
INSTALLED_APPS = [
    # ...
    'debug_toolbar',
    'patient',
]

# 启用Debug Toolbar中间件
MIDDLEWARE = [
    # ...
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# 配置允许Debug Toolbar显示的IP地址
INTERNAL_IPS = [
    '47.108.224.128',
]
# settings.py

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,
    'JQUERY_URL': '',  # 设置为空字符串以避免冲突
}

# 白名单豁验证
CSRF_EXEMPT_URLS = [
    r'^weChat/login$',  # 匹配/weChat/login URL
]
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent  20241119
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
SESSION_COOKIE_AGE = 60 * 30  # 设置会话为 30 分钟
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kbq3qk9zclb%j#3(g!8kky)(^km38qp=zdt*-3rd605d7!*x68'


ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patient.apps.PatientConfig',
    'drf_yasg',
    'corsheaders',   #20241103修改为了跨域

    'rest_framework',
     'drf_spectacular',
]
# 20250108 添加drf_spectacular
REST_FRAMEWORK = {
       'DEFAULT_AUTHENTICATION_CLASSES': (
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ),
   }
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',    #20241103修改为了跨域
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
#CORS_ALLOW_ALL_ORIGINS = True
# 指定允许的跨域源    20241103修改为了跨域
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8081",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
    "https://aiforoptometry.com",
    "https://www.aiforoptometry.com",
     "http://localhost:3000",
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-organization-id',
]

#  监听sql执行 最大的调试输出
DEBUG=True
# 启用凭据支持
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'eye.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 允许的主机名列表，可以是一个字面字符串，也可以是一个正则表达式
ALLOWED_HOSTS = ['47.108.224.128', 'aiforoptometry.com', 'www.aiforoptometry.com']  # 上传到服务器时要打开

WSGI_APPLICATION = 'eye.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {  'default': {      'ENGINE': 'django.db.backends.sqlite3',   'NAME': BASE_DIR / 'db.sqlite3',  }}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "patient",  # 数据库名称
        "USER": "root",
        "PASSWORD": "Xty-WwCc%xZ;123",
        "HOST": "47.108.224.128",  # 那台机器安装了mysql
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 日志配置

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/admin/eye/django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # 新增针对当前模块的logger配置
        '__name__': {  # 替换为你的视图模块的实际名称
            'handlers': ['file'],
            'level': 'DEBUG',  # 设置日志级别，可以根据需要调整为INFO、ERROR等
            'propagate': False,  # 不向父logger传播，仅在此处记录
        },
    },
}
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


